routes/admin.php
<?php 

Route::get('/',function(){
    return redirect()->route('admin.login');
});

Route::group(['namespace'=>'Admin'],function() {

        Route::get('/seller/register', 'RegisterController@showRegistrationForm')->name('admin.register');
        Route::post('/seller/register', 'RegisterController@create')->name('admin.registered');
        Route::get('login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'LoginController@login');

Route::group(['middleware' => 'auth:admin'], function () {

        Route::post('logout', 'LoginController@logout')->name('admin.logout');
        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
        Route::get('change-password', 'ChangePasswordController@changePassword')->name('change.password');
        Route::post('change-password', 'ChangePasswordController@changePasswordCreate')->name('change.password');

   });
});

Route::group(['middleware'=>'auth:admin'],function() {
   

    AdvancedRoute::controller('/category', 'Admin\CategoryController');
    AdvancedRoute::controller('/product', 'Admin\ProductController');
    AdvancedRoute::controller('/mail', 'Admin\MailController');
    AdvancedRoute::controller('/offer', 'Admin\OfferController');
    AdvancedRoute::controller('/seller', 'Admin\SellerController');


});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Product extends Model
{
    //
     use Sortable;

     public function getIconAttribute($value)
      {
        return asset('storage').'/'.$value;
      }

    public function category()
    {
    	 return $this->belongsTo(Category::class,'category_id','id');
    }
}

app/Http/Controllers/Admin/SellerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin;

class SellerController extends Controller
{
    //

     public function getIndex(Request $request)
    { 
        //$lists = Teacher::orderBy('id','desc')->get();

        $lists = new Admin();
        $per_page = 10;
        $search['per_page'] = $per_page;
        
        if (isset($request->per_page) && !empty($request->per_page)) {
            $per_page = $request->per_page;
            $search['per_page'] = $request->per_page;
        }
        if (isset($request->search) && !empty($request->search)) {
            $search_value = $request->search;
            $search['search'] = $search_value;
           
            $lists = $lists->where('name','like', '%'.$search_value.'%');
        }

        $lists = $lists->where('type','Seller')->sortable()->paginate($per_page);
        
        if($request->ajax()){
            return view('admin.seller.list',compact('lists','search'));
        }

        return view('admin.seller.index',compact('lists','search'));
    }

    public function anySellerDelete(Request $request)
    {  
    	$id = $request->id;
        Admin::where('id',$id)->where('type','Seller')->delete();
        return response()->json(true);
    }

    public function anySellerChangeStatus($id = null)
    { 
        $response =array('status'=>null,'row_id'=>null);
        $data = Admin::findOrFail($id);
        $data->status = ($data->status == 0?1:0);
        $data->save();
        $response =array('status'=>$data->status,'row_id'=>$data->id);
        return response()->json($response);
    }

}

resources/views/admin/seller/index.blade.php
@extends('admin.layouts.master')
@section('title','Seller')
@section('page_title','Seller')
@section('css')

@endsection
@section('breadcrumb')
  <ol class="breadcrumb">
    <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Seller</li>
  </ol>
@endsection
@section('content')
<div class="row" id="js_main_row">
  @include('admin.seller.list',$lists)
</div>
<!-- /.row -->
@include('admin.partials.delete_modal')
@include('admin.partials.status_modal')
@endsection
@section('js')

@endsection
@push('custom_script')
<script type="text/javascript">
</script>

@endpush

resources/views/admin/seller/list.blade.php
@include('common.flash')
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header with-border">
            {{-- <h3 class="box-title">Users</h3> --}}
            <span class="pull-right">
            <a id="js_back" href="{{ action('Admin\SellerController@getIndex') }}" class="btn btn-info" >Back</a>
          </span>
            <form id="search_form" action="{{ action('Admin\SellerController@getIndex') }}">
                <div class="row">
                    <div class="col-sm-1" >
                        <select name="" id="js_per_page" class="form-control input-sm">
                            @php
                                $per_page_arr = array(10,25,50,100);
                            @endphp
                            @foreach($per_page_arr as $per)
                                <option value="{{$per}}" {{$search['per_page'] == $per ? 'selected' : ''}}>{{$per}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-xs-4" >
                        <div class="input-group input-group-sm hidden-xs " >
                            
                            <input type="text" id="js_search_value" name="search" value="{{isset($search['search']) ? $search['search'] : ''}}" class="form-control pull-right" placeholder="Search">

                            <div class="input-group-btn">
                                <button type="button" id="js_search_button" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
      <div class="box-body">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th width="20px">#</th>
                    <th>Seller</th>
                    <th>@sortablelink('email', 'Email',['filter' => 'active, visible'],['class' => 'js_sorting'])</th>
                    
                    <th width="40px">Status</th>
                    <th width="60px">Actions</th>
                </tr>
            </thead>
            <tbody>
                @php $n =0; @endphp
                @forelse($lists as $list)
                    <tr class="test">
                        <td id="js_row_id_{{$list->id}}">{{++$n}}</td>
                        <!-- <td>{{$list->photo}}</td> -->
                       
                        {{-- <td><a href="{{$list->icon}}" target="_blank"><img src="{{$list->icon}}" width="50px" alt="image"></a></td> --}}
                        <td>{{$list->name}}</td>
                        <td>{{$list->email}}</td>
                        {{-- <td>{{$list->offer->offer}} %</td> --}}
                       
                        <td id="js_status_{{$list->id}}">
                            @if($list->status == 1)
                            <span class="label label-success">Active</span>
                            @else
                            <span class="label label-danger">Inactive</span>
                            @endif
                        </td>
                        <td>
                            @php
                            $action_array = array(
                            // 'view' => action('Admin\TeacherController@getTeacherView',['id'=>$list->id]),
                            // 'view timetable' => action('Admin\TeacherController@getTimeTable',['id'=>$list->id]),
                            // 'edit' => action('Admin\OfferController@getEdit',['id'=>$list->id]),
                            'delete' => action("Admin\SellerController@anySellerDelete"),
                            'status' => action("Admin\SellerController@anySellerChangeStatus",$list->id),
                            );
                            @endphp
                            @include('admin.partials.action',['action_array'=>$action_array,'list'=>$list,'edit_class'=>'js_modal_add_edit'])
                            
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="15" align="center">
                            Record not found
                        </td>
                    </tr>

                    @endforelse
            </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      @include('admin.partials.pagination',['lists'=>$lists])
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->